use blockbuster_gang;
insert into movie(title, genre)
values ('The Shawshank Redemption', 'Drama'),
       ('The Godfather', 'Crime'),
       ('The Dark Knight', 'Action'),
       ('Pulp Fiction', 'Crime'),
       ('Schindler''s List', 'History'),
       ('The Lord of the Rings: The Return of the King', 'Fantasy'),
       ('Fight Club', 'Drama'),
       ('Forrest Gump', 'Romance'),
       ('Inception', 'Sci-Fi'),
       ('The Matrix', 'Sci-Fi'),
       ('Goodfellas', 'Crime'),
       ('The Silence of the Lambs', 'Thriller'),
       ('Se7en', 'Mystery'),
       ('Interstellar', 'Sci-Fi'),
       ('Parasite', 'Drama'),
       ('Gladiator', 'Action'),
       ('The Green Mile', 'Fantasy'),
       ('Saving Private Ryan', 'War'),
       ('Spirited Away', 'Animation'),
       ('The Lion King', 'Animation');
